#ifndef MW_TARGET_HARDWARE_RESOURCES_H
#define MW_TARGET_HARDWARE_RESOURCES_H

#include "c2000BoardSupport.h"
#include "MW_f280015x_includes.h"
#include "c2000SchedulerTimer.h"
#define MW_RUNTIME_FLASHLOAD 1U
#define MW_CLOCKING_CPUCLOCKRATEMHZ 120U
#define MW_ADCA_EXTERNALREFERENCESELECTOR 0U
#define MW_ADCA_EXTERNALREFERENCEVREFHI 0U
#endif
